(()=>{'use strict';
const c=document.querySelector('#game'),ctx=c.getContext('2d'),$=s=>document.querySelector(s);
let W=0,H=0,D=1,last=0,on=false,paused=false,time=0,spawn=0,scroll=0,shake=0,score=0,combo=1,comboTimer=0,miss=0,best=+(localStorage.getItem('drop-zone-best')||0),zoom=1,zoomTarget=1,eventTimer=0,eventType='',eventLife=0;
let drops=[],targets=[],splats=[],parts=[],reactions=[],pinch=null,audio=null,ambientClock=0;
const p={x:0,y:0,vx:0,vy:0,alt:.55,ta:.55,bank:0,flap:0},inp={x:0,y:0,k:{}};
const missions=[['car',5,'Hit 5 cars'],['person',7,'Tag 7 pedestrians'],['building',4,'Splatter 4 rooftops'],['scooter',5,'Tag 5 scooters'],['crowd',6,'Crash a crowd'],['any',10,'Land 10 hits']];let mission={};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),choice=a=>a[Math.random()*a.length|0];
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);if(!p.x){p.x=W/2;p.y=H*.34}}addEventListener('resize',resize);resize();$('#best').textContent=best;
function ensureAudio(){if(audio)return;audio=new (window.AudioContext||window.webkitAudioContext)()}
function beep(freq=440,dur=.06,type='sine',gain=.035,delay=0){try{ensureAudio();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+dur)}catch{}}
function soundHit(perfect=false){beep(perfect?760:520,.05,'triangle',.045);beep(perfect?980:690,.08,'sine',.03,.045)}function haptic(pattern){if(navigator.vibrate)navigator.vibrate(pattern)}
function livesText(){const left=Math.max(0,4-Math.floor(miss/3));return '♥'.repeat(left)+'♡'.repeat(4-left)}function altitudeText(){return p.alt>.72?'HIGH':p.alt<.32?'LOW':'MID'}function altitudeMultiplier(){return p.alt>.72?1.6:p.alt>.5?1.25:p.alt<.25?.9:1}
function updateHud(){$('#score').textContent=score|0;$('#combo').textContent='×'+combo;$('#lives').textContent=livesText();$('#altitude').textContent=altitudeText();$('#best').textContent=Math.max(best,score|0);$('#missionText').textContent=mission.text+' '+mission.done+'/'+mission.need;$('#missionBar').style.width=mission.done/mission.need*100+'%'}
function nextMission(){const choices=missions.filter(m=>m[0]!==mission.type),a=choice(choices);mission={type:a[0],need:a[1],text:a[2],done:0}}
function reset(){score=0;combo=1;comboTimer=0;miss=0;time=0;spawn=0;scroll=0;eventTimer=8;eventType='';eventLife=0;drops=[];targets=[];splats=[];parts=[];reactions=[];p.x=W/2;p.y=H*.31;p.alt=p.ta=.55;p.vx=p.vy=p.bank=0;zoom=zoomTarget=1;mission={};nextMission();updateHud()}
function start(){ensureAudio();reset();on=true;paused=false;$('#menu').classList.add('hidden');$('#pauseMenu').classList.add('hidden');$('#hud').classList.remove('hidden');$('#controls').classList.remove('hidden');$('#zoomHint').classList.remove('hidden');setTimeout(()=>$('#zoomHint').classList.add('hidden'),3200);last=performance.now();requestAnimationFrame(loop)}
function end(reason='Flight over'){on=false;paused=false;best=Math.max(best,score|0);localStorage.setItem('drop-zone-best',best);$('#menu').classList.remove('hidden');$('#pauseMenu').classList.add('hidden');$('#hud').classList.add('hidden');$('#controls').classList.add('hidden');$('#zoomHint').classList.add('hidden');$('#eventBanner').classList.add('hidden');$('#tag').textContent=reason+' — '+(score|0)+' points. Best '+best;$('#start').textContent='FLY AGAIN';beep(130,.35,'sawtooth',.05);haptic([60,40,100])}
function setPaused(value){if(!on)return;paused=value;$('#pauseMenu').classList.toggle('hidden',!paused);if(!paused){last=performance.now();requestAnimationFrame(loop)}}
$('#start').onclick=start;$('#resume').onclick=()=>setPaused(false);$('#restart').onclick=start;$('#quit').onclick=()=>end('Flight ended');$('#pause').onclick=()=>setPaused(true);$('#home').onclick=()=>end('Flight ended');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),700)}
function announceEvent(type){eventType=type;eventLife=8;const names={wedding:'WEDDING PARTY!',market:'MERCATO RUSH!',vespa:'VESPA RALLY!',tourists:'TOUR BUS CROWD!'};$('#eventBanner').textContent=names[type];$('#eventBanner').classList.remove('hidden');toast(names[type]);beep(440,.08,'square',.035);beep(660,.12,'triangle',.03,.09)}
function addTarget(forceType){const lane=Math.random()*5|0,r=Math.random(),type=forceType||(r<.30?'car':r<.53?'person':r<.70?'scooter':r<.83?'building':'crowd');targets.push({type,x:W*(.1+lane*.2)+rnd(-18,18),y:H+80,w:type==='car'?34:type==='person'?15:type==='scooter'?24:type==='building'?64:45,h:type==='car'?60:type==='person'?25:type==='scooter'?41:type==='building'?68:42,s:type==='car'?rnd(95,150):type==='person'?rnd(35,66):type==='scooter'?rnd(82,130):type==='crowd'?rnd(28,46):0,v:type==='car'?135:type==='person'?185:type==='scooter'?225:type==='building'?110:260,hue:rnd(0,360),dir:Math.random()<.5?-1:1,react:0})}
function spawnEventWave(){const map={wedding:['crowd','person','person','crowd'],market:['crowd','person','scooter','person'],vespa:['scooter','scooter','scooter','car'],tourists:['crowd','crowd','person','person']};for(const t of map[eventType]||[])addTarget(t)}
function drop(){if(!on||paused||drops.length>4)return;const gy=p.y+92+p.alt*245/zoom;drops.push({gx:p.x+p.bank*7,gy,y:p.y,t:0,d:.34+p.alt*.56});beep(250,.035,'square',.023);haptic(12)}$('#drop').onpointerdown=e=>{e.preventDefault();drop()};
addEventListener('keydown',e=>{inp.k[e.code]=1;if(e.code==='Space'){e.preventDefault();drop()}if(!on&&e.code==='Enter')start();if(e.code==='KeyP'&&on)setPaused(!paused);if(e.code==='Equal'||e.code==='NumpadAdd')setZoom(zoomTarget+.1);if(e.code==='Minus'||e.code==='NumpadSubtract')setZoom(zoomTarget-.1)});addEventListener('keyup',e=>inp.k[e.code]=0);
function stick(el,knob,cb){let id=null;const mv=e=>{if(e.pointerId!==id)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,z=Math.min(r.width*.32,Math.hypot(dx,dy)),a=Math.atan2(dy,dx),xx=Math.cos(a)*z,yy=Math.sin(a)*z;knob.style.transform=`translate(${xx}px,${yy}px)`;cb(xx/(r.width*.32),yy/(r.width*.32))};el.onpointerdown=e=>{id=e.pointerId;el.setPointerCapture(id);mv(e)};el.onpointermove=mv;el.onpointerup=el.onpointercancel=e=>{if(e.pointerId===id){id=null;knob.style.transform='';cb(0,0)}}}stick($('#stick'),$('#knob'),(a,b)=>{inp.x=a;inp.y=b});
let aid=null,A=$('#alt'),AK=$('#altKnob');function moveAlt(e){if(e.pointerId!==aid)return;const r=A.getBoundingClientRect();p.ta=clamp(1-(e.clientY-r.top)/r.height,0,1);AK.style.bottom=7+p.ta*(r.height-50)+'px'}A.onpointerdown=e=>{aid=e.pointerId;A.setPointerCapture(aid);moveAlt(e)};A.onpointermove=moveAlt;A.onpointerup=A.onpointercancel=e=>{if(e.pointerId===aid)aid=null};
function setZoom(v){zoomTarget=clamp(v,.72,1.45)}$('#zoomIn').onclick=()=>setZoom(zoomTarget+.12);$('#zoomOut').onclick=()=>setZoom(zoomTarget-.12);
c.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){if(!pinch)pinch={a:e.pointerId,ax:e.clientX,ay:e.clientY,b:null,base:zoomTarget};else if(pinch.b===null){pinch.b=e.pointerId;pinch.bx=e.clientX;pinch.by=e.clientY;pinch.dist=Math.hypot(pinch.ax-pinch.bx,pinch.ay-pinch.by)}}});c.addEventListener('pointermove',e=>{if(!pinch)return;if(e.pointerId===pinch.a){pinch.ax=e.clientX;pinch.ay=e.clientY}else if(e.pointerId===pinch.b){pinch.bx=e.clientX;pinch.by=e.clientY}else return;if(pinch.b!==null)setZoom(pinch.base*Math.hypot(pinch.ax-pinch.bx,pinch.ay-pinch.by)/Math.max(30,pinch.dist))});c.addEventListener('pointerup',e=>{if(pinch&&(e.pointerId===pinch.a||e.pointerId===pinch.b))pinch=null});c.addEventListener('pointercancel',()=>pinch=null);
function reaction(t,text){reactions.push({x:t.x,y:t.y-25,text,l:1.2});t.react=1.2}
function hit(t,d){t.hit=1;const q=clamp(1-Math.hypot(t.x-d.gx,t.y-d.gy)/62,0,1),mult=altitudeMultiplier(),pts=Math.round(t.v*(.7+q*.9)*combo*mult);score+=pts;combo=Math.min(9,combo+1);comboTimer=2.35;shake=q>.8?9:5;soundHit(q>.82);haptic(q>.82?[20,25,30]:20);const sayings=q>.82?['MAMMA MIA!','PERFETTO!','BULLSEYE!','CHE COLPO!']:['DIRECT HIT!','SPLAT!','BEL COLPO!'];toast('+'+pts+' '+choice(sayings));reaction(t,choice(['🤌','😱','💢','🙈']));splats.push({x:d.gx,y:d.gy,r:9+q*16,l:1});for(let i=0;i<18;i++)parts.push({x:d.gx,y:d.gy,vx:rnd(-135,135),vy:rnd(-130,45),l:rnd(.35,.8),c:Math.random()<.3?'#ffd166':'#fff1d6'});if(mission.type==='any'||mission.type===t.type)mission.done++;if(mission.done>=mission.need){score+=1000;toast('MISSION +1000');beep(820,.1,'triangle',.045);nextMission()}updateHud()}
function missDrop(d){combo=1;miss++;shake=3;toast('MISSED! '+livesText());beep(150,.12,'sawtooth',.035);haptic([20,30,20]);splats.push({x:d.gx,y:d.gy,r:7,l:.5});updateHud()}
function update(dt){time+=dt;scroll=(scroll+(105+40*p.alt)*dt)%110;zoom+=(zoomTarget-zoom)*dt*7;ambientClock+=dt;if(ambientClock>5){ambientClock=0;beep(choice([330,392,440]),.06,'sine',.008)}const kx=(inp.k.KeyD||inp.k.ArrowRight?1:0)-(inp.k.KeyA||inp.k.ArrowLeft?1:0),ky=(inp.k.KeyS||inp.k.ArrowDown?1:0)-(inp.k.KeyW||inp.k.ArrowUp?1:0);if(inp.k.KeyQ)p.ta-=dt;if(inp.k.KeyE)p.ta+=dt;p.ta=clamp(p.ta,0,1);p.alt+=(p.ta-p.alt)*dt*5;const sx=clamp(inp.x+kx,-1,1),sy=clamp(inp.y+ky,-1,1);p.vx+=(sx*360-p.vx)*dt*6.5;p.vy+=(sy*275-p.vy)*dt*6.5;p.bank+=(sx-p.bank)*dt*7;p.flap+=dt*(7+Math.abs(sx)*3+Math.abs(sy)*2);p.x=clamp(p.x+p.vx*dt,34,W-34);p.y=clamp(p.y+p.vy*dt,88,H*.67);
spawn-=dt;if(spawn<=0){addTarget();if(eventLife>0&&Math.random()<.4)spawnEventWave();spawn=Math.max(.28,.72-time*.0018)}eventTimer-=dt;if(eventTimer<=0&&!eventType){announceEvent(choice(['wedding','market','vespa','tourists']));eventTimer=24}if(eventLife>0&&(eventLife-=dt)<=0){eventType='';$('#eventBanner').classList.add('hidden');eventTimer=16}
for(const t of targets){t.y-=(t.s+62+35*p.alt)*dt;if(t.type==='person'||t.type==='crowd')t.x+=Math.sin(time*2+t.hue)*8*dt;if(t.type==='scooter')t.x+=t.dir*12*dt;if(t.react>0)t.react-=dt}targets=targets.filter(t=>t.y>-120&&!t.hit);
for(const d of drops){d.t+=dt;const z=clamp(d.t/d.d,0,1);d.y=p.y+(d.gy-p.y)*z;if(z>=1&&!d.done){d.done=1;const f=targets.filter(t=>!t.hit).sort((a,b)=>Math.hypot(a.x-d.gx,a.y-d.gy)-Math.hypot(b.x-d.gx,b.y-d.gy))[0];if(f&&Math.abs(f.x-d.gx)<f.w*.7+18&&Math.abs(f.y-d.gy)<f.h*.65+18)hit(f,d);else missDrop(d)}}drops=drops.filter(d=>!d.done);splats.forEach(s=>s.l-=dt);splats=splats.filter(s=>s.l>0);for(const q of parts){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=150*dt;q.l-=dt}parts=parts.filter(q=>q.l>0);reactions.forEach(r=>{r.y-=18*dt;r.l-=dt});reactions=reactions.filter(r=>r.l>0);if(comboTimer>0&&(comboTimer-=dt)<=0){combo=1;updateHud()}if(miss>=12)end('Out of luck');shake*=.82;updateHud()}
function rr(a,b,w,h,r){ctx.beginPath();ctx.roundRect(a,b,w,h,r)}
function drawItaly(){ctx.fillStyle='#d5ad72';ctx.fillRect(0,0,W,H);const block=96/zoom,street=38/zoom,off=scroll/zoom;for(let gy=-block+off;gy<H+block;gy+=block){for(let gx=-block;gx<W+block;gx+=block){const col=Math.abs(((gx/block+gy/block)|0)%5);ctx.fillStyle=['#d77b55','#e7b867','#b95e4c','#e3c483','#cf8d5d'][col];rr(gx+street*.38,gy+street*.28,block-street*.58,block-street*.48,5);ctx.fill();ctx.fillStyle='#793c32';ctx.fillRect(gx+street*.38,gy+street*.28,block-street*.58,7/zoom);ctx.fillStyle='#f3ddad';for(let wx=gx+street*.53;wx<gx+block-street*.32;wx+=18/zoom)for(let wy=gy+street*.46;wy<gy+block-street*.25;wy+=18/zoom)ctx.fillRect(wx,wy,6/zoom,8/zoom);if(((gx+gy)/block|0)%3===0){ctx.strokeStyle='#f7f0dc';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(gx+street*.45,gy+street*.72);ctx.lineTo(gx+block-street*.25,gy+street*.72);ctx.stroke()}}}
ctx.fillStyle='#887461';for(let gx=block*.16;gx<W+block;gx+=block)ctx.fillRect(gx-street*.18,0,street*.36,H);for(let gy=block*.42-off;gy<H+block;gy+=block)ctx.fillRect(0,gy-street*.15,W,street*.3);ctx.strokeStyle='#f7e8c888';ctx.lineWidth=Math.max(1,2/zoom);ctx.setLineDash([12/zoom,14/zoom]);for(let gx=block*.16;gx<W+block;gx+=block){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,H);ctx.stroke()}for(let gy=block*.42-off;gy<H+block;gy+=block){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(W,gy);ctx.stroke()}ctx.setLineDash([]);
for(let i=0;i<26;i++){const tx=i*137%W,ty=(i*211+scroll*1.3)%H;ctx.fillStyle='#3c7d4c';ctx.beginPath();ctx.arc(tx,ty,7/zoom,0,Math.PI*2);ctx.fill()}for(let i=0;i<12;i++){const ax=(i*179+40)%W,ay=(i*149+scroll*.7)%H;ctx.fillStyle=['#c33','#f4c95d','#2f7d55'][i%3];ctx.beginPath();ctx.arc(ax,ay,6/zoom,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f6ead6';ctx.beginPath();ctx.moveTo(ax-9/zoom,ay);ctx.lineTo(ax+9/zoom,ay);ctx.stroke()}
ctx.fillStyle='#6aa5c7';ctx.beginPath();ctx.arc(W*.82,H*.22,27/zoom,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#eff8ff';ctx.lineWidth=3/zoom;ctx.stroke();ctx.fillStyle='#fff';ctx.font=`${15/zoom}px serif`;ctx.fillText('⛲',W*.82-9/zoom,H*.22+6/zoom);ctx.fillStyle='#52342c';ctx.fillRect(W*.1,H*.12,18/zoom,55/zoom);ctx.fillStyle='#9b3f32';ctx.beginPath();ctx.moveTo(W*.1-5/zoom,H*.12);ctx.lineTo(W*.1+9/zoom,H*.07);ctx.lineTo(W*.1+23/zoom,H*.12);ctx.closePath();ctx.fill()}
function drawTarget(t){ctx.save();ctx.translate(t.x,t.y);if(t.react>0)ctx.rotate(Math.sin(time*24)*.08);if(t.type==='car'){ctx.fillStyle=`hsl(${t.hue} 70% 52%)`;rr(-t.w/2,-t.h/2,t.w,t.h,7);ctx.fill();ctx.fillStyle='#dceeff';rr(-t.w*.32,-t.h*.27,t.w*.64,t.h*.25,4);ctx.fill();ctx.fillStyle='#202833';for(const [xx,yy] of [[-.55,-.32],[.45,-.32],[-.55,.16],[.45,.16]])ctx.fillRect(t.w*xx,t.h*yy,4,t.h*.18)}else if(t.type==='person'){ctx.fillStyle='#f2c49b';ctx.beginPath();ctx.arc(0,-8,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`hsl(${t.hue} 60% 45%)`;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(0,10);ctx.stroke();ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,1);ctx.lineTo(-6,7);ctx.moveTo(0,1);ctx.lineTo(6,7);ctx.moveTo(0,10);ctx.lineTo(-5,18);ctx.moveTo(0,10);ctx.lineTo(5,18);ctx.stroke()}else if(t.type==='scooter'){ctx.strokeStyle='#1e293b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(-6,12,5,0,Math.PI*2);ctx.arc(7,12,5,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=`hsl(${t.hue} 70% 50%)`;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-5,10);ctx.lineTo(4,1);ctx.lineTo(9,11);ctx.moveTo(4,1);ctx.lineTo(4,-7);ctx.stroke();ctx.fillStyle='#f2c49b';ctx.beginPath();ctx.arc(4,-12,5,0,Math.PI*2);ctx.fill()}else if(t.type==='crowd'){for(let i=0;i<5;i++){const a=i/5*Math.PI*2,rx=Math.cos(a)*13,ry=Math.sin(a)*9;ctx.fillStyle=`hsl(${(t.hue+i*55)%360} 65% 54%)`;ctx.beginPath();ctx.arc(rx,ry,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f2c49b';ctx.beginPath();ctx.arc(rx,ry-7,3.5,0,Math.PI*2);ctx.fill()}}else{ctx.fillStyle=`hsl(${t.hue} 35% 52%)`;rr(-t.w/2,-t.h/2,t.w,t.h,6);ctx.fill();ctx.fillStyle='#ead9af';ctx.fillRect(-t.w*.36,-t.h*.28,t.w*.72,t.h*.56);ctx.fillStyle='#983c30';ctx.beginPath();ctx.moveTo(-t.w*.43,-t.h*.28);ctx.lineTo(0,-t.h*.48);ctx.lineTo(t.w*.43,-t.h*.28);ctx.closePath();ctx.fill();ctx.fillStyle='#3f7047';ctx.fillRect(-5,-3,10,18)}ctx.restore()}
function drawBird(){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.bank*.22);const s=.82+p.alt*.34,flap=Math.sin(p.flap)*10;ctx.scale(s,s);ctx.shadowColor='#0008';ctx.shadowBlur=16;ctx.fillStyle='#d9dde3';ctx.beginPath();ctx.ellipse(0,0,22,30,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8e98a5';ctx.beginPath();ctx.ellipse(-19,-flap*.18,19,7,-.48-flap*.018,0,Math.PI*2);ctx.ellipse(19,-flap*.18,19,7,.48+flap*.018,0,Math.PI*2);ctx.fill();ctx.fillStyle='#44515f';ctx.beginPath();ctx.arc(0,-18,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#efb43f';ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(8,-20);ctx.lineTo(0,-18);ctx.closePath();ctx.fill();ctx.restore();const gy=p.y+92+p.alt*245/zoom;ctx.strokeStyle=p.alt>.72?'#ffd166cc':'#fff8';ctx.lineWidth=1.6;ctx.setLineDash([5,5]);ctx.beginPath();ctx.ellipse(p.x+p.bank*7,gy,19+9/zoom,10+5/zoom,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}
function draw(){ctx.save();ctx.translate(rnd(-shake,shake),rnd(-shake,shake));ctx.translate(W/2,H/2);ctx.scale(zoom,zoom);ctx.translate(-W/2,-H/2);drawItaly();for(const s of splats){ctx.globalAlpha=s.l;ctx.fillStyle='#f8f0df';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const t of targets)drawTarget(t);for(const d of drops){ctx.fillStyle='#fff4cf';ctx.beginPath();ctx.arc(d.gx,d.y,5+d.t*8,0,Math.PI*2);ctx.fill()}for(const q of parts){ctx.globalAlpha=Math.max(0,q.l*2);ctx.fillStyle=q.c;ctx.fillRect(q.x,q.y,3,3)}ctx.globalAlpha=1;for(const r of reactions){ctx.globalAlpha=clamp(r.l,0,1);ctx.font='22px serif';ctx.fillText(r.text,r.x-10,r.y)}ctx.globalAlpha=1;drawBird();ctx.restore()}
function loop(now){if(!on||paused)return;const dt=Math.min(.034,(now-last)/1000||.016);last=now;update(dt);draw();if(on&&!paused)requestAnimationFrame(loop)}draw();
})();