(()=>{'use strict';
const c=document.querySelector('#game'),x=c.getContext('2d'),$=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.random()*a.length|0];
let W=0,H=0,D=1,last=0,on=false,paused=false,time=0,spawn=0,score=0,combo=1,bestCombo=1,comboClock=0,missStreak=0,hearts=4,best=+(localStorage.getItem('drop-zone-best-v4')||0),shake=0,flash=0,slow=0,eventClock=11,eventType='',eventLife=0,audio=null,soundOn=localStorage.getItem('drop-zone-sound')!=='off';
let targets=[],drops=[],parts=[],splats=[],reactions=[],clouds=[];const input={x:0,y:0,k:{}};const p={x:0,y:0,vx:0,vy:0,alt:.5,ta:.5,bank:0,flap:0};
const districts=[{n:'PIAZZA',sky:'#a9dcff',road:'#d5ad72',roof:['#d77b55','#e7b867','#b95e4c']},{n:'CANAL',sky:'#90cce8',road:'#8bc2c6',roof:['#cb7655','#e6ba72','#af5545']},{n:'MARKET',sky:'#f3bd83',road:'#d6a56e',roof:['#ca5d43','#efbd69','#9c443c']},{n:'NIGHT',sky:'#26354d',road:'#3c475a',roof:['#70465c','#865242','#50405f']}];
const missions=[['car',6,'Hit 6 cars'],['person',8,'Tag 8 pedestrians'],['scooter',6,'Hit 6 scooters'],['crowd',5,'Disrupt 5 crowds'],['perfect',4,'Land 4 bullseyes'],['any',12,'Land 12 hits']];let mission={type:'any',need:10,done:0,text:'Land 10 hits'};
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0);if(!p.x){p.x=W/2;p.y=H*.3}clouds=Array.from({length:8},()=>({x:rnd(0,W),y:rnd(25,H*.28),s:rnd(.7,1.7)}))}addEventListener('resize',resize);resize();
function ensureAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)()}
function tone(f=440,d=.05,t='sine',g=.025,delay=0){if(!soundOn)return;try{ensureAudio();const o=audio.createOscillator(),v=audio.createGain(),at=audio.currentTime+delay;o.type=t;o.frequency.value=f;v.gain.setValueAtTime(g,at);v.gain.exponentialRampToValueAtTime(.0001,at+d);o.connect(v).connect(audio.destination);o.start(at);o.stop(at+d)}catch{}}
function buzz(v){if(navigator.vibrate)navigator.vibrate(v)}
function district(){return districts[Math.min(3,Math.floor(time/38))]}
function altData(){return p.alt>.74?['HIGH',2,.95]:p.alt>.43?['MID',1.35,.7]:['LOW',1,.48]}
function nextMission(){const m=pick(missions.filter(q=>q[0]!==mission.type));mission={type:m[0],need:m[1],done:0,text:m[2]}}
function livesText(){return '♥'.repeat(hearts)+'♡'.repeat(4-hearts)}
function hud(){const a=altData();$('#score').textContent=score|0;$('#combo').textContent='×'+combo;$('#lives').textContent=livesText();$('#altitude').textContent=a[0]+' ×'+a[1];$('#best').textContent=Math.max(best,score|0);$('#missionText').textContent=mission.text+' '+mission.done+'/'+mission.need;$('#missionBar').style.width=mission.done/mission.need*100+'%'}
function reset(){time=spawn=score=comboClock=missStreak=0;combo=bestCombo=1;hearts=4;shake=flash=slow=0;eventClock=10;eventType='';eventLife=0;targets=[];drops=[];parts=[];splats=[];reactions=[];p.x=W/2;p.y=H*.3;p.vx=p.vy=p.bank=0;p.alt=p.ta=.5;mission={type:'none'};nextMission();hud()}
function start(){ensureAudio();reset();on=true;paused=false;$('#menu').classList.add('hidden');$('#pauseMenu').classList.add('hidden');$('#hud').classList.remove('hidden');$('#controls').classList.remove('hidden');$('#zoomHint').textContent='Aim with the projected landing ring. Lead moving targets.';$('#zoomHint').classList.remove('hidden');setTimeout(()=>$('#zoomHint').classList.add('hidden'),3500);last=performance.now();requestAnimationFrame(loop)}
function end(reason='Flight over'){on=false;paused=false;best=Math.max(best,score|0);localStorage.setItem('drop-zone-best-v4',best);$('#menu').classList.remove('hidden');$('#pauseMenu').classList.add('hidden');$('#hud').classList.add('hidden');$('#controls').classList.add('hidden');$('#eventBanner').classList.add('hidden');$('#tag').textContent=reason+' — '+(score|0)+' points · Best combo ×'+bestCombo+' · Best '+best;$('#start').textContent='FLY AGAIN';tone(135,.3,'sawtooth',.05);buzz([50,35,90])}
function setPaused(v){if(!on)return;paused=v;$('#pauseMenu').classList.toggle('hidden',!v);if(!v){last=performance.now();requestAnimationFrame(loop)}}
$('#start').onclick=start;$('#resume').onclick=()=>setPaused(false);$('#restart').onclick=start;$('#quit').onclick=()=>end('Flight ended');$('#pause').onclick=()=>setPaused(true);$('#home').onclick=()=>end('Flight ended');
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),720)}
function banner(s){const e=$('#eventBanner');e.textContent=s;e.classList.remove('hidden');clearTimeout(banner.t);banner.t=setTimeout(()=>e.classList.add('hidden'),1000)}
function announce(type){eventType=type;eventLife=9;banner({wedding:'WEDDING PROCESSION!',market:'MERCATO RUSH!',vespa:'VESPA RALLY!',tour:'TOUR GROUP!'}[type]);tone(440,.07,'square',.03);tone(660,.1,'triangle',.025,.08)}
function addTarget(force){const r=Math.random(),type=force||(r<.28?'car':r<.52?'person':r<.72?'scooter':r<.86?'crowd':'building'),lane=Math.random()*6|0,spec={car:[40,64,145,150],person:[18,28,65,190],scooter:[26,42,120,235],crowd:[56,42,42,300],building:[72,58,0,125]}[type];targets.push({type,x:W*(.07+lane*.17)+rnd(-18,18),y:H+90,w:spec[0],h:spec[1],speed:spec[2],value:spec[3],dir:Math.random()<.5?-1:1,hue:rnd(0,360),phase:rnd(0,7),hit:false})}
function eventWave(){const m={wedding:['crowd','person','crowd'],market:['building','person','scooter','crowd'],vespa:['scooter','scooter','scooter','car'],tour:['crowd','crowd','person']};for(const t of m[eventType]||[])addTarget(t)}
function projected(){const a=altData(),fall=.4+p.alt*.9;return{x:p.x+p.vx*fall*.38,y:p.y+100+p.alt*Math.min(330,H*.42),fall}}
function drop(){if(!on||paused||drops.length>=5)return;const q=projected();drops.push({x:p.x,y:p.y+15,vx:p.vx*.38,vy:45,t:0,d:q.fall,done:false});tone(240,.04,'square',.022);buzz(10)}$('#drop').onpointerdown=e=>{e.preventDefault();drop()};
addEventListener('keydown',e=>{input.k[e.code]=1;if(e.code==='Space'){e.preventDefault();drop()}if(e.code==='KeyP'&&on)setPaused(!paused);if(!on&&e.code==='Enter')start()});addEventListener('keyup',e=>input.k[e.code]=0);
function stick(el,knob,cb){let id=null;const mv=e=>{if(e.pointerId!==id)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,m=r.width*.32,d=Math.hypot(dx,dy)||1,z=Math.min(m,d),xx=dx/d*z,yy=dy/d*z;knob.style.transform=`translate(${xx}px,${yy}px)`;cb(xx/m,yy/m)};el.onpointerdown=e=>{id=e.pointerId;el.setPointerCapture(id);mv(e)};el.onpointermove=mv;el.onpointerup=el.onpointercancel=e=>{if(e.pointerId===id){id=null;knob.style.transform='';cb(0,0)}}}stick($('#stick'),$('#knob'),(a,b)=>{input.x=a;input.y=b});
let aid=null,A=$('#alt'),AK=$('#altKnob');function moveAlt(e){if(e.pointerId!==aid)return;const r=A.getBoundingClientRect();p.ta=clamp(1-(e.clientY-r.top)/r.height,0,1);AK.style.bottom=7+p.ta*(r.height-50)+'px'}A.onpointerdown=e=>{aid=e.pointerId;A.setPointerCapture(aid);moveAlt(e)};A.onpointermove=moveAlt;A.onpointerup=A.onpointercancel=e=>{if(e.pointerId===aid)aid=null};
function hit(t,d){t.hit=true;const radius=Math.max(28,t.w*.66),dist=Math.hypot(t.x-d.x,t.y-d.y),precision=clamp(1-dist/radius,0,1),a=altData(),perfect=precision>.78,great=precision>.48,pts=Math.round(t.value*(.75+precision)*a[1]*combo);score+=pts;combo=Math.min(12,combo+1);bestCombo=Math.max(bestCombo,combo);comboClock=2.5;missStreak=0;shake=perfect?11:6;flash=perfect?.18:.08;slow=perfect?.12:0;tone(perfect?930:great?700:560,.06,'triangle',.04);tone(perfect?1220:great?900:720,.08,'sine',.025,.04);buzz(perfect?[18,18,30]:18);toast((perfect?'BULLSEYE ':great?'GREAT HIT ':'HIT ')+'+'+pts);splats.push({x:d.x,y:d.y,r:12+precision*18,l:1});for(let i=0;i<22;i++)parts.push({x:d.x,y:d.y,vx:rnd(-155,155),vy:rnd(-170,45),l:rnd(.35,.85),c:Math.random()<.35?'#ffd166':'#fff3d0'});reactions.push({x:d.x,y:d.y-18,text:pick(['🤌','😱','💢','🙈']),l:1.1});if(mission.type==='any'||mission.type===t.type||(mission.type==='perfect'&&perfect))mission.done++;if(mission.done>=mission.need){score+=900;banner('MISSION COMPLETE +900');nextMission()}hud()}
function miss(d){combo=1;missStreak++;shake=3;splats.push({x:d.x,y:d.y,r:7,l:.5});tone(165,.12,'sawtooth',.03);if(missStreak>=3){hearts--;missStreak=0;toast('3 MISSES — HEART LOST');buzz([25,30,40]);if(hearts<=0)end('Out of chances')}else toast('MISS · '+(3-missStreak)+' until damage');hud()}
function resolve(d){let f=null,dist=1e9;for(const t of targets){if(t.hit)continue;const z=Math.hypot(t.x-d.x,t.y-d.y);if(z<dist){dist=z;f=t}}if(f&&dist<Math.max(28,f.w*.66))hit(f,d);else miss(d)}
function update(dt){time+=dt;const kx=(input.k.KeyD||input.k.ArrowRight?1:0)-(input.k.KeyA||input.k.ArrowLeft?1:0),ky=(input.k.KeyS||input.k.ArrowDown?1:0)-(input.k.KeyW||input.k.ArrowUp?1:0);if(input.k.KeyQ)p.ta-=dt*.8;if(input.k.KeyE)p.ta+=dt*.8;p.ta=clamp(p.ta,0,1);p.alt+=(p.ta-p.alt)*dt*4.5;const sx=clamp(input.x+kx,-1,1),sy=clamp(input.y+ky,-1,1);p.vx+=(sx*310-p.vx)*dt*5.2;p.vy+=(sy*225-p.vy)*dt*5.2;p.bank+=(sx-p.bank)*dt*6;p.flap+=dt*(8+Math.abs(sx)*4);p.x=clamp(p.x+p.vx*dt,35,W-35);p.y=clamp(p.y+p.vy*dt,82,H*.58);
spawn-=dt;if(spawn<=0){addTarget();if(eventLife>0&&Math.random()<.36)eventWave();spawn=Math.max(.32,.82-time*.002)}eventClock-=dt;if(eventClock<=0&&!eventType){announce(pick(['wedding','market','vespa','tour']));eventClock=25}if(eventLife>0&&(eventLife-=dt)<=0){eventType='';eventClock=16}
for(const t of targets){t.y-=(t.speed+105+p.alt*45)*dt;if(t.type==='person'||t.type==='crowd')t.x+=Math.sin(time*2+t.phase)*10*dt;if(t.type==='scooter')t.x+=t.dir*18*dt;if(t.x<25||t.x>W-25)t.dir*=-1}targets=targets.filter(t=>t.y>-110&&!t.hit);
for(const d of drops){d.t+=dt;d.vy+=520*dt;d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.t>=d.d&&!d.done){d.done=true;resolve(d)}}drops=drops.filter(d=>!d.done&&d.y<H+60);
parts.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=180*dt;q.l-=dt});parts=parts.filter(q=>q.l>0);splats.forEach(s=>s.l-=dt);splats=splats.filter(s=>s.l>0);reactions.forEach(r=>{r.y-=25*dt;r.l-=dt});reactions=reactions.filter(r=>r.l>0);if(comboClock>0&&(comboClock-=dt)<=0)combo=1;shake*=.84;flash=Math.max(0,flash-dt);hud()}
function rr(a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r)}
function drawWorld(){const d=district();x.fillStyle=d.sky;x.fillRect(0,0,W,H);for(const q of clouds){q.x-=q.s*.12;if(q.x<-100)q.x=W+100;x.globalAlpha=.24;x.fillStyle='#fff';x.beginPath();x.ellipse(q.x,q.y,70*q.s,22*q.s,0,0,7);x.fill()}x.globalAlpha=1;const cell=105,off=(time*(75+p.alt*60))%cell;x.save();x.translate(0,-off);for(let y=-cell;y<H+cell*2;y+=cell)for(let xx=-20;xx<W+cell;xx+=cell){const col=Math.abs(((xx/cell+y/cell)|0)%d.roof.length);x.fillStyle=d.road;x.fillRect(xx,y,cell-5,cell-5);x.fillStyle=d.roof[col];rr(xx+16,y+13,cell-36,cell-32,7);x.fill();x.fillStyle='#fff1b8';for(let wy=y+27;wy<y+cell-26;wy+=22)for(let wx=xx+29;wx<xx+cell-28;wx+=24)x.fillRect(wx,wy,7,10);x.fillStyle='#73372e';x.fillRect(xx+15,y+13,cell-34,8)}x.restore();if(d.n==='CANAL'){x.fillStyle='#46a6b8aa';x.fillRect(W*.43,0,W*.14,H)}if(d.n==='NIGHT'){x.fillStyle='#07101d66';x.fillRect(0,0,W,H)}}
function drawTarget(t){x.save();x.translate(t.x,t.y);if(t.type==='car'){x.fillStyle=`hsl(${t.hue} 68% 48%)`;rr(-t.w/2,-t.h/2,t.w,t.h,8);x.fill();x.fillStyle='#bdeaff';x.fillRect(-t.w*.32,-t.h*.25,t.w*.64,t.h*.25)}else if(t.type==='person'){x.fillStyle='#f1bb82';x.beginPath();x.arc(0,-9,6,0,7);x.fill();x.fillStyle=`hsl(${t.hue} 60% 47%)`;rr(-6,-3,12,18,4);x.fill()}else if(t.type==='scooter'){x.fillStyle='#222';x.beginPath();x.arc(-8,13,5,0,7);x.arc(8,13,5,0,7);x.fill();x.strokeStyle=`hsl(${t.hue} 75% 52%)`;x.lineWidth=4;x.beginPath();x.moveTo(-8,9);x.lineTo(7,5);x.lineTo(9,-10);x.stroke();x.fillStyle='#f1bb82';x.beginPath();x.arc(5,-16,5,0,7);x.fill()}else if(t.type==='crowd'){for(let i=0;i<5;i++){x.fillStyle=`hsl(${t.hue+i*40} 60% 52%)`;x.beginPath();x.arc((i-2)*10,Math.sin(i)*5,7,0,7);x.fill()}}else{x.fillStyle=`hsl(${t.hue} 65% 55%)`;rr(-36,-28,72,56,8);x.fill();x.fillStyle='#fff8';for(let i=-25;i<30;i+=14)x.fillRect(i,-28,7,56)}x.restore()}
function drawBird(){x.save();x.translate(p.x,p.y);x.rotate(p.bank*.25);const wing=Math.sin(p.flap)*11;x.fillStyle='#dbe4ed';x.beginPath();x.ellipse(-14,wing*.35,24,9,-.35,0,7);x.ellipse(14,-wing*.35,24,9,.35,0,7);x.fill();x.fillStyle='#f6f8fb';x.beginPath();x.ellipse(0,0,18,25,0,0,7);x.fill();x.fillStyle='#687889';x.beginPath();x.arc(0,-17,13,0,7);x.fill();x.fillStyle='#ffae42';x.beginPath();x.moveTo(10,-18);x.lineTo(24,-14);x.lineTo(10,-10);x.fill();x.fillStyle='#fff';x.beginPath();x.arc(5,-20,3,0,7);x.fill();x.fillStyle='#111';x.beginPath();x.arc(6,-20,1.4,0,7);x.fill();x.restore()}
function drawAim(){const q=projected();let lock=false;x.save();x.strokeStyle='#ffffffbb';x.lineWidth=2;x.setLineDash([7,6]);x.beginPath();x.arc(q.x,q.y,31,0,7);x.stroke();x.setLineDash([]);for(const t of targets){const ty=t.y-(t.speed+105+p.alt*45)*q.fall;if(Math.hypot(t.x-q.x,ty-q.y)<40){lock=true;break}}if(lock){x.strokeStyle='#ffd166';x.lineWidth=4;x.beginPath();x.arc(q.x,q.y,38,0,7);x.stroke()}x.fillStyle=lock?'#ffd166':'#fff';x.font='900 11px sans-serif';x.textAlign='center';x.fillText(lock?'LEAD LOCK':q.fall.toFixed(1)+'s',q.x,q.y+52);x.restore()}
function draw(){x.save();if(shake)x.translate(rnd(-shake,shake),rnd(-shake,shake));drawWorld();for(const s of splats){x.globalAlpha=s.l;x.fillStyle='#fff0c9';x.beginPath();x.arc(s.x,s.y,s.r,0,7);x.fill()}x.globalAlpha=1;targets.forEach(drawTarget);for(const d of drops){x.fillStyle='#fff1d3';x.beginPath();x.ellipse(d.x,d.y,6,9,0,0,7);x.fill();x.strokeStyle='#ffffff88';x.beginPath();x.moveTo(d.x,d.y-8);x.lineTo(d.x-d.vx*.08,d.y-28);x.stroke()}for(const q of parts){x.globalAlpha=clamp(q.l*2,0,1);x.fillStyle=q.c;x.fillRect(q.x,q.y,4,4)}x.globalAlpha=1;for(const r of reactions){x.globalAlpha=r.l;x.font='26px sans-serif';x.fillText(r.text,r.x,r.y)}x.globalAlpha=1;drawAim();drawBird();if(flash){x.fillStyle=`rgba(255,255,255,${flash})`;x.fillRect(0,0,W,H)}x.restore()}
function loop(now){if(!on||paused)return;let dt=Math.min(.033,(now-last)/1000||.016);last=now;if(slow>0){slow-=dt;dt*=.38}update(dt);draw();requestAnimationFrame(loop)}draw();
})();